data:
  source_data_dir: "/kaggle/input/datasets/lucasiturriago/bananaripeness/Original"
  batch_size: 32
  img_size: 224
  num_workers: 4
  imagenet_mean: [0.485, 0.456, 0.406]
  imagenet_std: [0.229, 0.224, 0.225]
  use_augmentation: false

model:
  num_classes: 4
  pretrained: false
  backbone: "efficientnet"
  dropout_rate: 0.2

training:
  epochs: 20
  lr: 0.0001
  gamma: 0.94
  use_amp: true
  device: "cuda"
  seed: 42

experiment:
  name: "baseline_efficientnet_experiment"
  version: 0
  output_dir: "outputs/efficientnet/experiment_0_0"